// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NobleMushroom","status":true,"description":"ノベルゲーム総合プラグイン","parameters":{"表示タイプ初期値":"1","タイトル表示タイプ":"1","コマンド単位ウェイト":"ON","表示速度変数":"1","表示速度初期値":"2","クリック瞬間表示":"ON","クリック範囲限定":"ON","自動改行":"ON","相対フォントサイズ":"4","明朝体表示":"ON","ゴシック体表示":"OFF","固有フォント表示":"","選択肢接頭辞":"1","画面横サイズ":"0","画面縦サイズ":"0","モバイル画面横サイズ":"480","モバイル画面縦サイズ":"0","モバイルモード":"OFF","オートセーブ":"ON","ポーズ可能":"ON","オートセーブ名称":"オートセーブ","ロードコマンド":"ロード","Qセーブコマンド":"クイックセーブ","Qロードコマンド":"クイックロード"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"グリッドサイズ":"48","テストマップID":"1"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"ON","ピクチャ番号の変数番号":"11","ポインタX座標の変数番号":"12","ポインタY座標の変数番号":"13","タッチ操作抑制":"ON"}},
{"name":"MPP_SimpleTouch","status":true,"description":"【MMP ver.1.4】マウスやタッチ操作を変更します。","parameters":{"Long Press Time":"15"}}
];
